/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadsTidRouteImport } from './routes/threads/$tid'
import { Route as ForumsForumKeyRouteImport } from './routes/forums/$forumKey'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsTidRoute = ThreadsTidRouteImport.update({
  id: '/threads/$tid',
  path: '/threads/$tid',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsForumKeyRoute = ForumsForumKeyRouteImport.update({
  id: '/forums/$forumKey',
  path: '/forums/$forumKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/forums/$forumKey': typeof ForumsForumKeyRoute
  '/threads/$tid': typeof ThreadsTidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/forums/$forumKey': typeof ForumsForumKeyRoute
  '/threads/$tid': typeof ThreadsTidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/forums/$forumKey': typeof ForumsForumKeyRoute
  '/threads/$tid': typeof ThreadsTidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search' | '/forums/$forumKey' | '/threads/$tid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search' | '/forums/$forumKey' | '/threads/$tid'
  id: '__root__' | '/' | '/search' | '/forums/$forumKey' | '/threads/$tid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  ForumsForumKeyRoute: typeof ForumsForumKeyRoute
  ThreadsTidRoute: typeof ThreadsTidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$tid': {
      id: '/threads/$tid'
      path: '/threads/$tid'
      fullPath: '/threads/$tid'
      preLoaderRoute: typeof ThreadsTidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/$forumKey': {
      id: '/forums/$forumKey'
      path: '/forums/$forumKey'
      fullPath: '/forums/$forumKey'
      preLoaderRoute: typeof ForumsForumKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  ForumsForumKeyRoute: ForumsForumKeyRoute,
  ThreadsTidRoute: ThreadsTidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
